name: fast_gbk_example
version: 0.0.1
description: A sample command-line application for fast_gbk
dependencies:
  http: ^0.12.0
  dio: ^2.1.16
  gbk_codec: ^0.3.1
  fast_gbk:
    path: ../
dev_dependencies:
#  unittest: any
