name: fast_gbk
description: a fast gbk codec, support GBK encoding and decoding with stream api.
version: 0.1.1+1
homepage: https://github.com/lixiangthinker/fast_gbk
author: lixiang <lixiangthinker@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  dio: ^2.1.16
